namespace game.Constants
{
    public enum TextCategory
    {
        MainMenu,
        General,
        Time,
        Alerts,
        Settings,
        Credits,
        RoleBlock,
        Abilities,
        CauseOfDeath,
        Goals,
        Voting,
        Teams,
        RoleCategories,
        RoleProperties,
        Messages,
        RoleBook,
        CurrentRole,
        GameEnd,
        PlayerNames,
        Graveyard,
        MultiDevice,
        Hints,
        LobbyPlayersStatus,
        Contact,
        RolePack,
        RolePackTexts
    }
}